---

- name: start vault-server container
  become: yes
  docker_container:
    name: vault-server
    image: vault:1.3.2
    command: server
    capabilities:
      - IPC_LOCK
    volumes:
      - /root/vault/file:/vault/file
      - /root/vault/config:/vault/config
      - /root/vault/logs:/vault/logs
    ports:
      - "8200:8200"
    env:
      VAULT_SKIP_VERIFY: "1"
    state: started

